package com.ranchopro.journalApp.scheduler;

import com.ranchopro.journalApp.cache.AppCache;
import com.ranchopro.journalApp.entity.JournalEntry;
import com.ranchopro.journalApp.entity.User;
import com.ranchopro.journalApp.enums.Sentiment;
import com.ranchopro.journalApp.repository.UserRepositoryImpl;
import com.ranchopro.journalApp.service.EmailService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Component
public class UserScheduler {

    @Autowired
    private EmailService emailService;

    @Autowired
    private AppCache appCache;


    @Autowired
    private UserRepositoryImpl userRepository;

    // in this the users last 7 days entries as string is taken and filtered their content and mail is send to them on email about their analysis automate things here
    @Scheduled(cron = "0 0 9 * * SUN")
    // it means it will run on every sunday 9 morning this exp is generated by cron generator
    public void fetchUsersAndSendMail() {
        List<User> users = userRepository.getUsersForSentimentAnalysis();
        for (User user : users) {
            List<JournalEntry> journalEntries = user.getJournalEntriesList();
            List<Sentiment> sentiments = journalEntries.stream().filter(x -> x.getDate().isAfter(LocalDateTime.now().minus(7, ChronoUnit.DAYS))).map(x -> x.getSentiment()).collect(Collectors.toList());
            Map<Sentiment, Integer> sentimentCounts = new HashMap<>();
            for (Sentiment sentiment : sentiments) {
                if (sentiment != null)
                    sentimentCounts.put(sentiment, sentimentCounts.getOrDefault(sentiment, 0) + 1);
            }
            Sentiment mostFrequentSentiment = null;
            int maxCount = 0;
            for (Map.Entry<Sentiment, Integer> entry : sentimentCounts.entrySet()) {
                if (entry.getValue() > maxCount) {
                    maxCount = entry.getValue();
                    mostFrequentSentiment = entry.getKey();
                }
            }
            if (mostFrequentSentiment != null) {
                emailService.sendEmail(user.getEmail(), "Sentiment for last 7 Days", mostFrequentSentiment.toString());
            }


        }
    }

    //this will refresh the Catch and fetch data from database in every 5 min
    @Scheduled(cron = "0 0/10 * ? * *")
    public void clearAppCatche() {
        appCache.init();
    }
}
